### ISSUE TITLE
Hide underline style of text

### ISSUE THREAD

**Issue by SaXz2** [Quorafind/Outliner.MD#36]
![image](https://github.com/Quorafind/Outliner.MD/assets/52444119/4429a756-825f-4e85-bf8f-620490ac7613)

现在内嵌的内容都会添加一个下划线有些碍眼

**Comment by Quorafind** [comment]
您可以通过简单的 css 来控制这个变化：

```css
.internal-embed.is-loaded.embedded-part .markdown-source-view.mod-cm6 .cm-line {
    text-decoration: inherit;
}
```
