### ISSUE TITLE
Style: Suggestions for block embed

### ISSUE THREAD

**Issue by enneaa** [Quorafind/Outliner.MD#38]
Embedded content definitely needs to be distinguished from the main text, otherwise, users won’t know if they are editing the embedded content or the main text. However, the embedded content doesn’t need to be too different from the main text; it still needs to blend in. Embedded content is essentially a mirror of the original text.

I looked at the embedded content styles used in a few different applications. The most elegant is probably Workflowy. For main text, the unordered list bullets are round, but for embedded content, they are square. Logseq uses a slightly darker background color for embedded content, as does Siyuan Note.

I think there are several ways to distinguish embedded content. One way is to retain a link button that jumps to the original text. This makes it obvious that it’s embedded content. However, this only shows where the embedded content starts, not where it ends. Another way is to add a vertical line to the left or right side of the embedded content. In Obsidian, the native style is to add a vertical line to the left side, while a plugin author provided a style that adds a vertical line to the right side.

嵌入内容肯定是要和正文内容进行区分的，不然用户不知道自己编辑的是嵌入内容还是正文内容。
不过嵌入内容也没必要和正文区分过大，还是要融入到正文中来，嵌入内容相当于原文的镜像。
我看了下用过的几个软件嵌入内容样式。
最优雅的应该是workflowy，如果是正文，大纲前的无序列表的点是圆点，如果是嵌入内容，就是方点。
logseq是给嵌入内容加一个稍深一点的背景色，思源笔记也是。

我感觉要区分嵌入内容，有几种方式。
一是保留跳转到原文的链接按钮，一看就知道这是嵌入，不过仅仅是这样的话，就只知道嵌入内容从哪开始，但不知道从哪介绍。
二是在嵌入内容左侧或右侧加一条竖线。ob原生的是和引用样式一样，在左侧加一条竖线，然后插件作者提供的嵌入样式是在右侧加一条竖线。

**Comment by Quorafind** [comment]
关于嵌入样式：

对于行内嵌入，roamresearch 和logseq 都采用的是下划线：

![Clip_2024-05-22_15-13-17](https://github.com/Quorafind/Outliner.MD/assets/13215013/3cd042ae-6a7b-4b3f-829e-41e04cf52554)

如果希望背景颜色高亮，可以引用下述的 css：

```css
.internal-embed.is-loaded:has(.markdown-source-view) {
    background: var(--background-secondary);
}
```

关于下述建议的第一点：

![Clip_2024-05-22_15-09-12](https://github.com/Quorafind/Outliner.MD/assets/13215013/6b98c939-3408-4878-98a9-4a5634b5dfa7)


关于下述建议的第二点：

你可以很轻松地将右侧的转移到左侧，只需要将原来写着 right:0 的地方修改成 left: 0 即可，方便你复制的代码：

```css
.internal-embed.is-loaded:not(.embedded-part):has(.markdown-source-view):before {
	content: ' ';
	width: 2px;
	position: absolute;
	height: 100%;
	top: 0;
	left: 0; 
	background-color: var(--color-accent);
	transition: background-color 200ms ease-in-out, border-color 200ms ease-in-out, opacity 200ms ease-in-out;
}
 
.internal-embed.is-loaded:not(.embedded-part):has(.markdown-source-view):hover:before {
	width: 3px;
	transition: background-color 200ms ease-in-out, border-color 200ms ease-in-out, opacity 200ms ease-in-out;
}
```

后续会将上述内容选摘到文档，感谢建议
