### ISSUE TITLE
[Share css] A css for the new divider line with title

### ISSUE THREAD

**Issue by Moyf** [Quorafind/Outliner.MD#71]
![image](https://github.com/user-attachments/assets/06475dff-07fe-4bd0-a69d-ff9a7314e86c)

```css
.omd-section-line {
    text-align: right;
    opacity: 0.8;
    padding-right: 1em;
    margin: 0px !important;
    &::before {
        content: "🔖";
    }
}

/* 新的笔记本的分隔线样式 */
.omd-section-line hr {
    border-width: 1px;
    border-radius: 3px;
    border-style: dashed;
    border-color: var(--text-normal);
    opacity: 0.5;
}
```

**Comment by Moyf** [comment]
Another style with less line height:
![image](https://github.com/user-attachments/assets/57e9c3c8-7a4c-4739-ad06-ad357cbb267a)

```css

.cm-line:has(.omd-section-line) {
    line-height: 0em;
}

.omd-section-line {
    text-align: right;
    opacity: 0.8;
    padding-right: 1em;
    margin: 0px !important;
    /*line-height: 1.5em;*/
    &::before {
        content: "🔖";
    }
}

/* 新的笔记本的分隔线样式 */
.omd-section-line hr {
    border-width: 1px;
    border-radius: 3px;
    border-style: dashed;
    border-color: var(--text-normal);
    opacity: 0.5;
    max-width: 80%;
}
```
