### ISSUE TITLE
Text Embed in Edit Mode is off center in update

### ISSUE THREAD

**Issue by rossoj85** [Quorafind/Outliner.MD#90]
Hello. 

Recently updated to the newest version (1.12). Something added to the CSS is causing the embeds to appear far to the left, outside of the border of the open workspace for me. This is only happening in the new version. 

![image](https://github.com/user-attachments/assets/86ed4874-2b53-4e28-bc5c-9dffbe5c821b)

I replaced the css file with the old 1.8 version and it seems to have solved the problem. 

![image](https://github.com/user-attachments/assets/9ae48e58-cd7f-42d5-a4ea-1d471db9fbfc)

Thought you should be aware, and thanks for the plugin!

**Comment by wwgb** [comment]
I suspect it might be because you have enabled the Pixel Banner plugin, as I've also encountered this issue. I added this CSS snippet to resolve it: 
```css
.pixel-banner .internal-embed .cm-sizer:first-of-type:has(.embed-editor) {
  padding-top: inherit;
}
```
